# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
        ('inv_app', '0003_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_page', models.IntegerField(choices=[(10, 10), (25, 25), (50, 50), (100, 100), (250, 250)], default=100, verbose_name='Photos per page')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery', verbose_name='Album')),
            ],
        ),
    ]
